version: "3"
services:
  app:
    build: ./dockerfile/php
    volumes:
      - ./:/work

####################################################
  web:
    image: nginx:1.20-alpine
    ports:
      - 8100:80
    volumes:
      - ./:/work
      - ./dockerfile/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

####################################################
  db:
    image: mysql:8.0
    # build: ./dockerfile/mysql
    volumes: 
    # データを永続化したいときは、コンテナの外にデータを置く必要がある。
      # - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=laravel_local
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      # - TZ=Asia/Tokyo
    # ports:
    #   - "3306:3306"
# volumes:
#   db-store:

######################

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=phper
      - PMA_PASSWORD=secret
    links:
      - db
    ports:
      - 8081:80
    volumes:
        - "./phpmyadmin/sessions:/sessions"
